# NumPy Practice Exercises

Solve each question in the code cell below it. Do not just re-run the lab examples — use **different numbers/data** than what was shown in class so you are actually writing the logic yourself.

Run each cell with **Shift + Enter** and check that your output makes sense before moving to the next question.

### Q1. Creating a 1-D array
Create a 1-D NumPy array containing 6 numbers of your choice. Print the array and print its type using `type()`.

In [ ]:
# Write your code here
import numpy as n
a=n.array([1,2,3,4,5,7])
print(a)
print(type(a))


[1 2 3 4 5 7]
<class 'numpy.ndarray'>


### Q2. Creating a 2-D array
Create a 2-D NumPy array with 3 rows and 2 columns (any numbers). Print the array.

In [ ]:
# Write your code here
import numpy as np
b=np.array([[1,2],[3,4],[5,6]])
print(b)


[[1 2]
 [3 4]
 [5 6]]


### Q3. Creating a 3-D array
Create a 3-D NumPy array made up of two 2x3 matrices (2 blocks, each with 2 rows and 3 columns). Print the array.

In [ ]:
# Write your code here
import numpy as np
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8,9],[10, 11, 12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Q4. Checking the number of dimensions
Using the three arrays you created in Q1, Q2, and Q3, print the number of dimensions of each using the `.ndim` attribute.

In [ ]:
# Write your code here
print(a.ndim)
print(b.ndim)
print(arr.ndim)

1
2
3


### Q5. Accessing elements with indexing
Create a 2-D array with 2 rows and 5 columns of your own numbers.
1. Print the 3rd element of the 1st row using positive indexing.
2. Print the last element of the 2nd row using **negative** indexing.

In [ ]:
# Write your code here
import numpy as np
d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("3rd element of 1st row:", d[0,2])
print("last element of 2nd row:",d[1,-1])



3rd element of 1st row: 3
last element of 2nd row: 10


### Q6. Accessing elements in a 3-D array
Using the 3-D array you created in Q3, access and print one specific element using three indices, e.g. `arr[block, row, col]`.

In [ ]:
# Write your code here
import numpy as np
arr=np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
print(arr[0,0,2])

3


### Q7. Checking data type
Create one NumPy array of integers and one NumPy array that contains at least one decimal number. Print the `.dtype` of each and explain in a comment why they are different.

In [ ]:
# Write your code here
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(arr.dtype)
arr1=np.array([1,2.5,5,7])
print(arr1)
print(arr1.dtype)

[1 2 3 4]
int64
[1.  2.5 5.  7. ]
float64


### Q8. Copy vs View
Create a 1-D array. Make a **copy** of it using `.copy()` and a **view** of it using `.view()`. Change the first element of the original array, then print the original array, the copy, and the view. In a comment, explain what you observe and why.

In [ ]:
# Write your code here
import numpy as np
arr=np.array([10,20,30,40])
copy_arr=arr.copy()
view_arr=arr.view()
arr[0]=100
print("Original array",arr)
print("copy array",copy_arr)
print("view array",view_arr)

Original array [100  20  30  40]
copy array [10 20 30 40]
view array [100  20  30  40]


### Q9. Shape of an array
1. Create a 2-D array with 3 rows and 4 columns and print its `.shape`.
2. Create a 1-D array of 4 numbers with `ndmin=5` and print both the array and its shape.

In [ ]:
# Write your code here
import numpy as np
arr=np.array([[1,2,3,4],[5,7,8,9],[12,34,45,67]])
print(arr)
print(arr.shape)
arr2=np.array([1,3,5,7], ndmin=5)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  7  8  9]
 [12 34 45 67]]
(3, 4)
(1, 1, 1, 1, 4)


### Q10. Reshaping arrays
Create a 1-D array with 15 elements. Reshape it into a 2-D array with 3 rows and 5 columns using `.reshape()`. Print the result.

In [ ]:
# Write your code here
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,12,23,34,45,56])
print(arr)
arr2=arr.reshape(3,5)
print(arr2)


[ 1  2  3  4  5  6  7  8  9 10 12 23 34 45 56]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [12 23 34 45 56]]


### Q11. Linear algebra with NumPy
Solve the following system of equations using `np.linalg.solve()`:

2x + y = 11

x + 3y = 18

Print the values of x and y.

In [ ]:
# Write your code here
import numpy as np
a=np.array([[2,1],[1,3]])
b=np.array([11,18])
solution=np.linalg.solve(a,b)
x,y=solution
print("x:",x)
print("y:",y)

x: 3.0
y: 5.0


### Q12. arange, zeros, and ones
1. Use `np.zeros()` to create a 4x2 array of zeros.
2. Use `np.ones()` to create a 3x3 array of ones.
3. Use `np.arange()` to create an array of numbers from 5 to 30 with a step of 5.

Print all three.

In [ ]:
# Write your code here
import numpy as np
arr1=np.zeros((4,2))
arr2=np.ones((3,3))
arr3=np.arange(5,30,5)
print(arr1)
print(arr2)
print(arr3)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 5 10 15 20 25]


### Q13. Why NumPy is faster than plain Python
Create two Python lists of 500,000 numbers each. Time how long it takes to add them element-by-element using a Python loop (or list comprehension). Then convert both lists to NumPy arrays and time how long it takes to add them using `+`. Print both times and, in a comment, state which was faster and roughly by how much.

In [ ]:
# Write your code here
import numpy as np
import time
list1 = list(range(500000))
list2 = list(range(500000))
start = time.time()
c = (a[i] + b[i] for i in range(500000))
python_time = time.time() - start
a = np.array(a)
b = np.array(b)
start = time.time()
c = a + b
numpy_time = time.time() - start
print("Python time:", python_time)
print("NumPy time:", numpy_time)
print(c.shape)


Python time: 0.00017547607421875
NumPy time: 0.00010347366333007812
(2, 2)


### Q14. Vectors vs matrices
Create a 1-D NumPy array representing a single customer's features: `[height_cm, weight_kg, age]` (make up your own values). Then create a 2-D NumPy array representing 4 different customers with the same 3 features each. Print the `.shape` and `.ndim` of both arrays.

In [ ]:
# Write your code here
import numpy as np
customer1=np.array([172,25,55])
customers = np.array([
    [170, 65, 20],
    [165, 55, 21],
    [180, 75, 25],
    [160, 50, 19]
])
print("One customer:")
print(customer1)
print("Shape:", customer1.shape)
print("Dimensions:", customer1.ndim)
print("\nFour customers:")
print(customers)
print("Shape:", customers.shape)
print("Dimensions:", customers.ndim)

One customer:
[172  25  55]
Shape: (3,)
Dimensions: 1

Four customers:
[[170  65  20]
 [165  55  21]
 [180  75  25]
 [160  50  19]]
Shape: (4, 3)
Dimensions: 2


### Q15. Indexing and slicing to build X and y
Create a 2-D array with 6 rows and 3 columns, where the last column is a target label (0 or 1) and the first two columns are features (make up your own numbers).
1. Print the first 3 rows only.
2. Print only the first column, for all rows.
3. Split the array into `X` (all columns except the last) and `y` (only the last column), and print both.

In [ ]:
# Write your code here
import numpy as np
data = np.array([[10, 20, 0],[15, 25, 1],[12, 18, 0],[20, 30, 1],[25, 35, 1],[14, 22, 0]])
print("First 3 rows:")
print(data[:3])
print("\nFirst column:")
print(data[:, 0])
X = data[:, :-1]
y = data[:, -1]
print("\nX:")
print(X)
print("\ny:")
print(y)


First 3 rows:
[[10 20  0]
 [15 25  1]
 [12 18  0]]

First column:
[10 15 12 20 25 14]

X:
[[10 20]
 [15 25]
 [12 18]
 [20 30]
 [25 35]
 [14 22]]

y:
[0 1 0 1 1 0]


### Q16. Vectorized operations and boolean masking
Create a 1-D NumPy array of 8 exam scores (0-100) of your choice. Without using any loop:
1. Add 5 bonus marks to every score and print the result.
2. Print a boolean array showing which scores are 50 or above.
3. Print only the scores that are 50 or above using boolean masking.

In [ ]:
# Write your code here
import numpy as np
scores = np.array([45, 67, 32, 80, 55, 49, 90, 72])
bonus_scores = scores + 5
print("Scores after bonus:")
print(bonus_scores)
mask = scores >= 50
print("\nBoolean array:")
print(mask)
print("\nScores 50 or above:")
print(scores[mask])


Scores after bonus:
[50 72 37 85 60 54 95 77]

Boolean array:
[False  True False  True  True False  True  True]

Scores 50 or above:
[67 80 55 90 72]
